name: CI

on:
  pull_request:
    paths:
      - '*.yaml'
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        #### Modify below here to match your project ####
        file:
          - athom-cb02
          - athom-garage-door
          - athom-mini-switch
          - athom-presence-sensor
          - athom-relay-board-x1
          - athom-relay-board-x2
          - athom-relay-board-x4
          - athom-relay-board-x8
          - athom-rgb-light
          - athom-rgbct-light
          - athom-rgbw-light
          - athom-rgbww-light
          - athom-smart-plug-v2
          - athom-smart-plug
          - athom-sw01-v2
          - athom-sw01
          - athom-sw02-v2
          - athom-sw02
          - athom-sw03
          - athom-sw04
          - athom-wall-outlet
          - athom-without-relay-plug
        #### Modify above here to match your project ####

        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v4.0.3
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}